apiVersion: apps/v1
kind: Deployment
metadata:
  name: underwater-app-github
  labels:
    app: octopus-underwater-app
spec:
  selector:
    matchLabels:
        app: octopus-underwater-app
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: octopus-underwater-app
    spec:
      containers:
        - name: octopus-underwater-app
          image: 207567801874.dkr.ecr.us-east-1.amazonaws.com/octopus-underwater-app:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          env:
            - name: MONGODB_URI
              value: "mongodb://mongo:password@192.168.0.66:27017"
            - name: SECRET_KEY
              value: "wizexercise.txt"
---
apiVersion: v1
kind: Service
metadata:
  name: service-nlb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: app
  selector:
    app: octopus-underwater-app
